use anyhow::Result;
use serde_json::json;

use crate::agent::AssistantAgent;
use crate::truncate_utf8;

use super::types::{AiSection, FacetSummary, QuantitativeStats, RecapProgress};

const SECTION_MAX_TOKENS: u32 = 1_500;
const AT_A_GLANCE_MAX_TOKENS: u32 = 1_200;

/// All section keys generated by the recap pipeline (in display order).
pub const SECTION_ORDER: &[(&str, &str)] = &[
    ("project_areas", "What you work on"),
    ("interaction_style", "How you use OpenComputer"),
    ("what_works", "What's working well"),
    ("friction_analysis", "Where things get stuck"),
    ("agent_tool_optimization", "Agent & tool optimization"),
    (
        "memory_skill_recommendations",
        "Memory & skill recommendations",
    ),
    ("cost_optimization", "Cost optimization"),
    ("suggestions", "Suggestions"),
    ("on_the_horizon", "On the horizon"),
    ("fun_ending", "Memorable moment"),
    ("at_a_glance", "At a glance"),
];

/// Generate every AI section in parallel (except `at_a_glance`, which depends
/// on the others and runs last).
pub async fn generate_all_sections<F>(
    agent: &AssistantAgent,
    facets: &FacetSummary,
    quant: &QuantitativeStats,
    progress: F,
) -> Result<Vec<AiSection>>
where
    F: Fn(RecapProgress) + Send + Sync,
{
    use futures_util::future::join_all;

    let context_json = build_context_json(facets, quant);
    let context_str = serde_json::to_string(&context_json).unwrap_or_default();

    // Sections to run in parallel (excluding at_a_glance).
    let parallel_keys: Vec<(&str, &str)> = SECTION_ORDER
        .iter()
        .filter(|(k, _)| *k != "at_a_glance")
        .copied()
        .collect();

    let total = SECTION_ORDER.len() as u32;
    progress(RecapProgress::GeneratingSections {
        completed: 0,
        total,
    });

    let futs: Vec<_> = parallel_keys
        .iter()
        .map(|(key, title)| run_section(agent, key, title, &context_str))
        .collect();
    let results = join_all(futs).await;

    let mut sections: Vec<AiSection> = Vec::with_capacity(SECTION_ORDER.len());
    let mut completed = 0u32;
    for ((key, title), res) in parallel_keys.iter().zip(results.into_iter()) {
        completed += 1;
        match res {
            Ok(md) => sections.push(AiSection {
                key: key.to_string(),
                title: title.to_string(),
                markdown: md,
            }),
            Err(e) => {
                app_warn!(
                    "recap",
                    "sections",
                    "section '{}' failed: {}",
                    key,
                    truncate_utf8(&e.to_string(), 256)
                );
                sections.push(AiSection {
                    key: key.to_string(),
                    title: title.to_string(),
                    markdown: String::from("_Section unavailable._"),
                });
            }
        }
        progress(RecapProgress::GeneratingSections { completed, total });
    }

    // ── At a glance: built from the other sections' outputs ──
    let glance_input = sections_for_summary(&sections);
    match run_at_a_glance(agent, &glance_input).await {
        Ok(md) => {
            sections.insert(
                0,
                AiSection {
                    key: "at_a_glance".to_string(),
                    title: "At a glance".to_string(),
                    markdown: md,
                },
            );
        }
        Err(e) => {
            app_warn!(
                "recap",
                "sections",
                "at_a_glance failed: {}",
                truncate_utf8(&e.to_string(), 256)
            );
            sections.insert(
                0,
                AiSection {
                    key: "at_a_glance".to_string(),
                    title: "At a glance".to_string(),
                    markdown: String::from("_Summary unavailable._"),
                },
            );
        }
    }
    progress(RecapProgress::GeneratingSections {
        completed: total,
        total,
    });

    Ok(sections)
}

fn build_context_json(facets: &FacetSummary, quant: &QuantitativeStats) -> serde_json::Value {
    json!({
        "facetCounts": {
            "totalFacets": facets.total_facets,
            "goalHistogram": facets.goal_histogram,
            "outcomeDistribution": facets.outcome_distribution,
            "sessionTypeDistribution": facets.session_type_distribution,
            "frictionTop": facets.friction_top,
            "satisfactionDistribution": facets.satisfaction_distribution,
            "repeatUserInstructions": facets.repeat_user_instructions,
            "successExamples": facets.success_examples,
            "frictionExamples": facets.friction_examples,
        },
        "quantitative": {
            "overview": quant.overview,
            "health": quant.health,
            "costTrend": {
                "totalCostUsd": quant.cost_trend.total_cost_usd,
                "avgDailyCostUsd": quant.cost_trend.avg_daily_cost_usd,
                "peakDay": quant.cost_trend.peak_day,
                "peakCostUsd": quant.cost_trend.peak_cost_usd,
                "points": quant.cost_trend.points.iter().take(14).collect::<Vec<_>>(),
            },
            "topSessions": quant.top_sessions.iter().take(5).collect::<Vec<_>>(),
            "modelEfficiency": quant.model_efficiency,
            "hourly": quant.hourly,
            "heatmapMax": quant.heatmap.max_value,
        }
    })
}

fn sections_for_summary(sections: &[AiSection]) -> String {
    let mut s = String::new();
    for sec in sections {
        s.push_str("## ");
        s.push_str(&sec.title);
        s.push('\n');
        s.push_str(truncate_utf8(&sec.markdown, 1_500));
        s.push_str("\n\n");
    }
    s
}

async fn run_section(
    agent: &AssistantAgent,
    key: &str,
    title: &str,
    context_json: &str,
) -> Result<String> {
    let instruction = section_prompt(key, title, context_json);
    app_debug!("recap", "sections", "running section '{}'", key);
    let res = agent.side_query(&instruction, SECTION_MAX_TOKENS).await?;
    Ok(res.text.trim().to_string())
}

async fn run_at_a_glance(agent: &AssistantAgent, sections_md: &str) -> Result<String> {
    let prompt = format!(
        "Below are several analysis sections from a usage report.\n\
         Write a concise 'At a glance' summary in markdown with FOUR short subsections:\n\
         1. **What's working** — 1-2 sentences\n\
         2. **What's hindering** — 1-2 sentences\n\
         3. **Quick wins** — 2-3 bullet points referencing earlier sections\n\
         4. **Ambitious next moves** — 1-2 sentences\n\
         Be specific, no fluff, no prefixes like 'Sure!'.\n\n\
         SECTIONS:\n{}",
        truncate_utf8(sections_md, 12_000)
    );
    let res = agent.side_query(&prompt, AT_A_GLANCE_MAX_TOKENS).await?;
    Ok(res.text.trim().to_string())
}

fn section_prompt(key: &str, title: &str, context_json: &str) -> String {
    let body = match key {
        "project_areas" =>
            "Identify the 3-5 main project areas the user worked on this period. \
             For each: a short title, an estimated session-share percentage, and 1-2 sentences \
             describing what they were doing.",
        "interaction_style" =>
            "Analyse HOW the user interacts with the assistant: cadence, command style, level of \
             autonomy, common patterns. Two short paragraphs followed by a one-line 'Key pattern:' \
             takeaway.",
        "what_works" =>
            "List 3 impressive workflows or accomplishments from this period. \
             For each: a bold title, then 1-2 sentences describing what the user did and why it worked.",
        "friction_analysis" =>
            "Identify 3 distinct friction categories the user hit. For each: a bold title, \
             a 1-sentence description, and 2 concrete examples (paraphrased) drawn from \
             frictionExamples in the context.",
        "agent_tool_optimization" =>
            "Recommend Agent and tool configuration changes specific to OpenComputer. \
             Look at modelEfficiency, frictionTop (esp. tool_errors), and topSessions. \
             Output 2-4 bullet points each starting with a concrete action verb.",
        "memory_skill_recommendations" =>
            "Look at repeatUserInstructions: turn 2-4 of the most repeated instructions into \
             memory entries the user should add (use OpenComputer's /remember command), and \
             suggest 1-2 skills to enable based on observed patterns. Use bullet points.",
        "cost_optimization" =>
            "Look at modelEfficiency, costTrend.totalCostUsd, and peak day. Suggest 2-3 \
             specific cost optimizations (cheaper models for low-stakes tasks, batching, etc.). \
             Be concrete with model names and rough $ savings if possible.",
        "suggestions" =>
            "Suggest 2-3 OpenComputer features the user should try next based on observed patterns: \
             skills, plan mode, sub-agents, ask_user_question tool, MCP servers, side_query, etc. \
             Also list any AGENTS.md / memory.md additions that would prevent repeated instructions. \
             Use bullets.",
        "on_the_horizon" =>
            "Suggest 2-3 ambitious workflows the user could try as models improve: \
             multi-agent pipelines, automated daily standups, scheduled cron-driven research, etc. \
             For each: a bold title, what's possible (1-2 sentences), and a copyable starter prompt.",
        "fun_ending" =>
            "Find ONE memorable moment from successExamples or frictionExamples and write a brief \
             personable note (2-3 sentences). End with a single emoji.",
        _ => "Summarise the data in 2-3 sentences.",
    };
    format!(
        "You are writing one section of a coaching report for an OpenComputer power user. \
         The report is in markdown.\n\
         SECTION TITLE: {title}\n\
         INSTRUCTIONS: {body}\n\
         Output ONLY the markdown body of this section (no header line, no code fences).\n\
         CONTEXT JSON:\n{context}",
        title = title,
        body = body,
        context = truncate_utf8(context_json, 12_000),
    )
}
