import type { ProviderTemplate } from "../types"

export const infrastructureTemplates: ProviderTemplate[] = [
  // ── 基础设施 / 聚合 Provider ──
  {
    key: "openrouter",
    name: "OpenRouter",
    description: "多模型聚合网关，一个 Key 用数百个模型",
    icon: "🔀",
    apiType: "openai-chat",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyPlaceholder: "sk-or-...",
    requiresApiKey: true,
    models: [
      {
        id: "auto",
        name: "OpenRouter Auto",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "google/gemini-2.5-pro-preview",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.55,
        costOutput: 2.19,
      },
      {
        id: "openrouter/hunter-alpha",
        name: "Hunter Alpha",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openrouter/healer-alpha",
        name: "Healer Alpha",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "groq",
    name: "Groq",
    description: "超高速 LPU 推理",
    icon: "🚀",
    apiType: "openai-chat",
    baseUrl: "https://api.groq.com/openai",
    apiKeyPlaceholder: "gsk_...",
    requiresApiKey: true,
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.59,
        costOutput: 0.79,
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.24,
        costOutput: 0.24,
      },
    ],
  },
  {
    key: "nvidia",
    name: "NVIDIA",
    description: "NVIDIA AI Endpoints",
    icon: "💚",
    apiType: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyPlaceholder: "nvapi-...",
    requiresApiKey: true,
    models: [
      {
        id: "nvidia/llama-3.1-nemotron-70b-instruct",
        name: "Llama 3.1 Nemotron 70B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "meta/llama-3.3-70b-instruct",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
        name: "Mistral NeMo Minitron 8B",
        inputTypes: ["text"],
        contextWindow: 8192,
        maxTokens: 2048,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "together",
    name: "Together AI",
    description: "开源模型云推理平台",
    icon: "🤝",
    apiType: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.5,
        costOutput: 2.8,
      },
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7 Fp8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.45,
        costOutput: 2.0,
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B",
        inputTypes: ["text", "image"],
        contextWindow: 10000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.18,
        costOutput: 0.59,
      },
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick 17B",
        inputTypes: ["text", "image"],
        contextWindow: 20000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.27,
        costOutput: 0.85,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2 Instruct",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 1.0,
        costOutput: 3.0,
      },
    ],
  },
  {
    key: "huggingface",
    name: "Hugging Face",
    description: "HF Inference API 开源模型推理",
    icon: "🤗",
    apiType: "openai-chat",
    baseUrl: "https://router.huggingface.co/v1",
    apiKeyPlaceholder: "hf_...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "byteplus",
    name: "BytePlus (海外火山)",
    description: "BytePlus AI 国际版大模型平台",
    icon: "🔥",
    apiType: "openai-chat",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "seed-1-8-251228",
        name: "Seed 1.8",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "chutes",
    name: "Chutes (TEE)",
    description: "TEE 可信执行环境 AI 推理",
    icon: "🔒",
    apiType: "openai-chat",
    baseUrl: "https://llm.chutes.ai/v1",
    apiKeyPlaceholder: "cpk_...",
    requiresApiKey: true,
    models: [
      {
        id: "zai-org/GLM-4.7-TEE",
        name: "GLM-4.7 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "moonshotai/Kimi-K2.5-TEE",
        name: "Kimi K2.5 TEE",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.2,
      },
      {
        id: "deepseek-ai/DeepSeek-V3-0324-TEE",
        name: "DeepSeek V3 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.25,
        costOutput: 1.0,
      },
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.08,
        costOutput: 0.24,
      },
    ],
  },
  {
    key: "cloudflare-ai",
    name: "Cloudflare AI Gateway",
    description: "Cloudflare AI 网关代理",
    icon: "☁️",
    apiType: "openai-chat",
    baseUrl: "https://gateway.ai.cloudflare.com/v1/{accountId}/{gatewayId}",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
    ],
  },
]
