import type { ProviderTemplate } from "../types"

export const internationalTemplates: ProviderTemplate[] = [
  // ── 国际 Provider ──
  {
    key: "anthropic",
    name: "Anthropic",
    description: "Claude 系列模型",
    icon: "🟤",
    apiType: "anthropic",
    baseUrl: "https://api.anthropic.com",
    apiKeyPlaceholder: "sk-ant-...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 15.0,
        costOutput: 75.0,
      },
      {
        id: "claude-haiku-3-5",
        name: "Claude Haiku 3.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.25,
        costOutput: 1.25,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "openai",
    name: "OpenAI",
    description: "GPT 系列模型 (Responses API)",
    icon: "🟢",
    apiType: "openai-responses",
    baseUrl: "https://api.openai.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "o3",
        name: "GPT o3",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 40.0,
      },
      {
        id: "o4-mini",
        name: "GPT o4-mini",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
    ],
  },
  {
    key: "openai-chat",
    name: "OpenAI (Chat)",
    description: "GPT 系列 — Chat Completions API",
    icon: "💬",
    apiType: "openai-chat",
    baseUrl: "https://api.openai.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "o3",
        name: "GPT o3",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 40.0,
      },
      {
        id: "o4-mini",
        name: "GPT o4-mini",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
    ],
  },
  {
    key: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek 系列推理模型",
    icon: "🔵",
    apiType: "openai-chat",
    baseUrl: "https://api.deepseek.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek V3",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.27,
        costOutput: 1.1,
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.55,
        costOutput: 2.19,
      },
    ],
  },
  {
    key: "google-gemini",
    name: "Google Gemini",
    description: "Gemini 系列多模态模型",
    icon: "💎",
    apiType: "openai-chat",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    apiKeyPlaceholder: "AIza...",
    requiresApiKey: true,
    models: [
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.15,
        costOutput: 0.6,
      },
    ],
  },
  {
    key: "xai",
    name: "xAI",
    description: "Grok 系列模型",
    icon: "✖️",
    apiType: "openai-chat",
    baseUrl: "https://api.x.ai/v1",
    apiKeyPlaceholder: "xai-...",
    requiresApiKey: true,
    models: [
      {
        id: "grok-4",
        name: "Grok 4",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-4-fast",
        name: "Grok 4 Fast",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 0.5,
      },
      {
        id: "grok-3",
        name: "Grok 3",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-3-mini",
        name: "Grok 3 Mini",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.5,
      },
      {
        id: "grok-code-fast-1",
        name: "Grok Code Fast",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 10000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.5,
      },
    ],
  },
  {
    key: "mistral",
    name: "Mistral",
    description: "Mistral 系列欧洲模型",
    icon: "🟣",
    apiType: "openai-chat",
    baseUrl: "https://api.mistral.ai/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.5,
        costOutput: 1.5,
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "devstral-medium-latest",
        name: "Devstral 2",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "magistral-small",
        name: "Magistral Small",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 40000,
        reasoning: true,
        costInput: 0.5,
        costOutput: 1.5,
      },
      {
        id: "mistral-medium-2508",
        name: "Mistral Medium 3.1",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.3,
      },
      {
        id: "pixtral-large-latest",
        name: "Pixtral Large",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 2.0,
        costOutput: 6.0,
      },
    ],
  },
]
