import type { ProviderTemplate } from "../types"

export const localTemplates: ProviderTemplate[] = [
  // ── 本地 / 自托管 Provider ──
  {
    key: "litellm",
    name: "LiteLLM",
    description: "统一 LLM API 代理网关",
    icon: "🔗",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:4000",
    apiKeyPlaceholder: "...",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        // LiteLLM 是代理网关，可路由到任意付费上游——单价取决于用户接的是谁，故未标价
        // 而非免费（vLLM / LM Studio / SGLang 是本机推理，占位符标 0 才对）。
        costInput: null,
        costOutput: null,
      },
    ],
  },
  {
    key: "ollama",
    name: "Ollama",
    description: "本地 + 云端模型推理，无需 API Key",
    icon: "🦙",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:11434",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      // 云端条目走 ollama.com 包月订阅（官方 pricing 按 GPU 时长计费、不按 token 数），
      // 故与本机模型同样标 0 = 明确不按 token 计费。标 null 会回退估算表，按 glm-5 等
      // 直连厂商单价给包月用户报出一笔不存在的账。
      {
        id: "glm-5.2:cloud",
        name: "GLM 5.2 (云端)",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2.5:cloud",
        name: "Kimi K2.5 (云端)",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax-m2.7:cloud",
        name: "MiniMax M2.7 (云端)",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-5.1:cloud",
        name: "GLM-5.1 (云端)",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4.7-flash",
        name: "GLM 4.7 Flash",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3:32b",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "vllm",
    name: "vLLM",
    description: "高性能本地推理引擎",
    icon: "⚙️",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:8000",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "lm-studio",
    name: "LM Studio",
    description: "桌面端本地模型推理",
    icon: "🖥️",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:1234",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "sglang",
    name: "SGLang",
    description: "高性能本地推理引擎",
    icon: "⚡",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:30000",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: [],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
]
