//! Builtin 工具分发条目（阶段 2.5：由 `execution.rs` 静态 match 机械迁移，
//! 行为零变化——每个条目的表达式与原 match 臂逐字对应，仅 `dispatch_ctx`
//! 更名 `ctx`、裸模块路径补 `super::`）。
//!
//! 新增内置工具：在此加条目（勿在 dispatch 里重新写 match 臂）；特征 crate
//! 的工具走 `registry::register_external_tools`（装配期）。

use super::registry::{tool_handler, BuiltinToolEntry};

#[rustfmt::skip]
pub(crate) fn builtin_entries() -> Vec<BuiltinToolEntry> {
    vec![
        BuiltinToolEntry { name: super::TOOL_EXEC, aliases: &[], handler: tool_handler!(|args, ctx| super::exec::tool_exec(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_PROCESS, aliases: &[], handler: tool_handler!(|args, ctx| super::process::tool_process(args).await) },
        BuiltinToolEntry { name: super::TOOL_READ, aliases: &["read_file"], handler: tool_handler!(|args, ctx| super::read::tool_read_file(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_WRITE, aliases: &["write_file"], handler: tool_handler!(|args, ctx| super::write::tool_write_file(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_EDIT, aliases: &["patch_file"], handler: tool_handler!(|args, ctx| super::edit::tool_edit(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_LS, aliases: &["list_dir"], handler: tool_handler!(|args, ctx| super::ls::tool_ls(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_LSP, aliases: &[], handler: tool_handler!(|args, ctx| super::lsp::tool_lsp(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_GREP, aliases: &[], handler: tool_handler!(|args, ctx| super::grep::tool_grep(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_FIND, aliases: &[], handler: tool_handler!(|args, ctx| super::find::tool_find(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_APPLY_PATCH, aliases: &[], handler: tool_handler!(|args, ctx| super::apply_patch::tool_apply_patch(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_WEB_SEARCH, aliases: &[], handler: tool_handler!(|args, ctx| super::web_search::tool_web_search(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_WEB_FETCH, aliases: &[], handler: tool_handler!(|args, ctx| super::web_fetch::tool_web_fetch(args).await) },
        BuiltinToolEntry { name: super::TOOL_SAVE_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::memory::tool_save_memory(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_RECALL_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::memory::tool_recall_memory(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_UPDATE_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::memory::tool_update_memory(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_DELETE_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::memory::tool_delete_memory(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_UPDATE_CORE_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::memory::tool_update_core_memory(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_CORE_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::core_memory::tool_core_memory(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_PROJECT_MEMORY, aliases: &[], handler: tool_handler!(|args, ctx| super::project_memory::tool_project_memory(args, ctx).await) },
        // `manage_cron` 的 handler 随 ha-cron 迁出，由 `ha_cron::wire()` 注册外部
        // 分发条目；schema 仍在 definitions::core_tools。
        BuiltinToolEntry { name: super::TOOL_SEND_NOTIFICATION, aliases: &[], handler: tool_handler!(|args, ctx| super::notification::tool_send_notification(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_SUBAGENT, aliases: &[], handler: tool_handler!(|args, ctx| super::subagent::tool_subagent(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_TEAM, aliases: &[], handler: tool_handler!(|args, ctx| super::team::tool_team(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_WORKFLOW, aliases: &[], handler: tool_handler!(|args, ctx| super::workflow_tool::tool_workflow(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_MEMORY_GET, aliases: &[], handler: tool_handler!(|args, ctx| super::memory::tool_memory_get(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_CREATE, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_create(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_READ, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_read(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_UPDATE, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_update(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_PATCH, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_patch(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_APPEND, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_append(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_DELETE, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_delete(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_SEARCH, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_search(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_LINK, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_link(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_BACKLINKS, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_backlinks(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_BY_TAG, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_by_tag(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_TAGS, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_tags(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_RENAME, aliases: &[super::TOOL_NOTE_MOVE], handler: tool_handler!(|args, ctx| super::note::tool_note_rename(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_SET_FRONTMATTER, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_set_frontmatter(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_ASSIGN_BLOCK, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_assign_block(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_BROKEN_LINKS, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_broken_links(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_ORPHANS, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_orphans(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_GRAPH, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_graph(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_SIMILAR, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_similar(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_RELATED, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_related(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_SUGGEST_LINKS, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_suggest_links(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_DISTILL, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_distill(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_NOTE_MOC, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_note_moc(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_KNOWLEDGE_RECALL, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_knowledge_recall(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_SESSION_TO_NOTE, aliases: &[], handler: tool_handler!(|args, ctx| super::note::tool_session_to_note(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_AGENTS_LIST, aliases: &[], handler: tool_handler!(|args, ctx| super::agents::tool_agents_list(args).await) },
        BuiltinToolEntry { name: super::TOOL_SESSIONS_LIST, aliases: &[], handler: tool_handler!(|args, ctx| super::sessions::tool_sessions_list(args).await) },
        BuiltinToolEntry { name: super::TOOL_SESSION_STATUS, aliases: &[], handler: tool_handler!(|args, ctx| super::sessions::tool_session_status(args).await) },
        BuiltinToolEntry { name: super::TOOL_SESSIONS_SEARCH, aliases: &[], handler: tool_handler!(|args, ctx| super::sessions::tool_sessions_search(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_SESSIONS_HISTORY, aliases: &[], handler: tool_handler!(|args, ctx| super::sessions::tool_sessions_history(args).await) },
        BuiltinToolEntry { name: super::TOOL_SESSIONS_SEND, aliases: &[], handler: tool_handler!(|args, ctx| Box::pin(super::sessions::tool_sessions_send(args, ctx)).await) },
        BuiltinToolEntry { name: super::TOOL_IMAGE, aliases: &[], handler: tool_handler!(|args, ctx| super::image::tool_image(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_ISSUE_REPORT, aliases: &[], handler: tool_handler!(|args, ctx| super::issue_report::tool_issue_report(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_PDF, aliases: &[], handler: tool_handler!(|args, ctx| super::pdf::tool_pdf(args).await) },
        BuiltinToolEntry { name: super::TOOL_ASK_USER_QUESTION, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::ask_user_question::execute(args, ctx.session_id.as_deref()).await)) },
        BuiltinToolEntry { name: super::TOOL_ENTER_PLAN_MODE, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::enter_plan_mode::execute(args, ctx.session_id.as_deref()).await)) },
        BuiltinToolEntry { name: super::TOOL_SUBMIT_PLAN, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::submit_plan::execute(args, ctx.session_id.as_deref()).await)) },
        BuiltinToolEntry { name: super::TOOL_TASK_CREATE, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::task::tool_task_create(args, ctx.session_id.as_deref()).await)) },
        BuiltinToolEntry { name: super::TOOL_TASK_UPDATE, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::task::tool_task_update(args, ctx.session_id.as_deref()).await)) },
        BuiltinToolEntry { name: super::TOOL_TASK_LIST, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::task::tool_task_list(args, ctx.session_id.as_deref()).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_STATUS, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_status(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_PREPARE_CONTRACT, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_prepare_contract(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_CHECKPOINT, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_checkpoint(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_RECORD_EVIDENCE, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_record_evidence(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_EVALUATE, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_evaluate(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_FINISH_REQUEST, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_finish_request(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_GOAL_BLOCK_REQUEST, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::goal::tool_goal_block_request(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_LOOP_STATUS, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::loop_tool::tool_loop_status(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_LOOP_RESCHEDULE, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::loop_tool::tool_loop_reschedule(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_LOOP_STOP, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::loop_tool::tool_loop_stop(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_LOOP_RECORD_PROGRESS, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::loop_tool::tool_loop_record_progress(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_LOOP_WATCH, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::loop_tool::tool_loop_watch(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_LOOP_UNWATCH, aliases: &[], handler: tool_handler!(|args, ctx| Ok(super::loop_tool::tool_loop_unwatch(args, ctx).await)) },
        BuiltinToolEntry { name: super::TOOL_JOB_STATUS, aliases: &[], handler: tool_handler!(|args, ctx| super::job_status::tool_job_status(args, ctx.session_id.as_deref()).await) },
        BuiltinToolEntry { name: super::TOOL_SCHEDULE_WAKEUP, aliases: &[], handler: tool_handler!(|args, ctx| super::schedule_wakeup::tool_schedule_wakeup(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_RUNTIME_CANCEL, aliases: &[], handler: tool_handler!(|args, ctx| super::runtime_cancel::tool_runtime_cancel(args).await) },
        BuiltinToolEntry { name: super::TOOL_TOOL_SEARCH, aliases: &[], handler: tool_handler!(|args, ctx| super::tool_search::tool_search(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_PEEK_SESSIONS, aliases: &[], handler: tool_handler!(|args, ctx| crate::awareness::run_peek_sessions(args, ctx.session_id.as_deref()) .map_err(|e| anyhow::anyhow!(e))) },
        BuiltinToolEntry { name: super::TOOL_GET_SETTINGS, aliases: &[], handler: tool_handler!(|args, ctx| super::settings::tool_get_settings(args).await) },
        BuiltinToolEntry { name: super::TOOL_UPDATE_SETTINGS, aliases: &[], handler: tool_handler!(|args, ctx| super::settings::tool_update_settings(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_LIST_SETTINGS_BACKUPS, aliases: &[], handler: tool_handler!(|args, ctx| super::settings::tool_list_settings_backups(args).await) },
        BuiltinToolEntry { name: super::TOOL_RESTORE_SETTINGS_BACKUP, aliases: &[], handler: tool_handler!(|args, ctx| super::settings::tool_restore_settings_backup(args).await) },
        BuiltinToolEntry { name: super::TOOL_SEND_ATTACHMENT, aliases: &[], handler: tool_handler!(|args, ctx| super::send_attachment::tool_send_attachment(args, ctx).await) },
        BuiltinToolEntry { name: super::TOOL_SKILL, aliases: &[], handler: tool_handler!(|args, ctx| super::skill::tool_skill(args, ctx).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DOCX_CREATE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::docx::execute_create(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DOCX_GET_BLOCKS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::docx::execute_get_blocks(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DOCX_APPEND_BLOCK, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::docx::execute_append_block(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DOCX_UPDATE_BLOCK_TEXT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::docx::execute_update_block_text(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_LIST_RECORDS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_list_records(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_SEARCH_RECORDS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_search_records(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_CREATE_RECORD, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_create_record(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_BATCH_UPDATE_RECORDS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_batch_update_records(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_LIST_VIEWS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_list_views(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_GET_VIEW, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_get_view(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_BITABLE_LIST_DASHBOARDS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::bitable::execute_list_dashboards(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DRIVE_LIST_FILES, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::drive::execute_list_files(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DRIVE_UPLOAD_MEDIA, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::drive::execute_upload_media(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_DRIVE_DOWNLOAD_MEDIA, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::drive::execute_download_media(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_WIKI_GET_NODE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::wiki::execute_get_node(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_APPROVAL_CREATE_INSTANCE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::approval::execute_create_instance(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_APPROVAL_GET_INSTANCE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::approval::execute_get_instance(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_APPROVAL_CANCEL_INSTANCE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::approval::execute_cancel_instance(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_APPROVAL_LIST_INSTANCES, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::approval::execute_list_instances(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_APPROVAL_SUBSCRIBE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::approval::execute_subscribe(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CALENDAR_LIST, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::calendar::execute_list(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CALENDAR_CREATE_EVENT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::calendar::execute_create_event(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CALENDAR_LIST_EVENTS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::calendar::execute_list_events(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CALENDAR_UPDATE_EVENT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::calendar::execute_update_event(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CALENDAR_DELETE_EVENT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::calendar::execute_delete_event(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CALENDAR_ATTENDEES_CREATE, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::calendar::execute_attendees_create(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CONTACT_GET_USER, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::contact::execute_get_user(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CONTACT_BATCH_GET_USERS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::contact::execute_batch_get_users(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CONTACT_GET_DEPARTMENT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::contact::execute_get_department(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_CONTACT_SEARCH_USERS_BY_DEPARTMENT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::contact::execute_search_users_by_department(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_HIRE_LIST_JOBS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::hire::execute_list_jobs(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_HIRE_GET_JOB, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::hire::execute_get_job(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_HIRE_LIST_TALENTS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::hire::execute_list_talents(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_HIRE_GET_TALENT, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::hire::execute_get_talent(args).await) },
        BuiltinToolEntry { name: super::feishu::TOOL_HIRE_LIST_APPLICATIONS, aliases: &[], handler: tool_handler!(|args, ctx| super::feishu::hire::execute_list_applications(args).await) },
    ]
}
