import type { ProviderTemplate } from "./types"

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  // ── 国际 Provider ──
  {
    key: "anthropic",
    name: "Anthropic",
    description: "Claude 系列模型",
    icon: "🟤",
    apiType: "anthropic",
    baseUrl: "https://api.anthropic.com",
    apiKeyPlaceholder: "sk-ant-...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 15.0,
        costOutput: 75.0,
      },
      {
        id: "claude-haiku-3-5",
        name: "Claude Haiku 3.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.25,
        costOutput: 1.25,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "openai",
    name: "OpenAI",
    description: "GPT 系列模型 (Responses API)",
    icon: "🟢",
    apiType: "openai-responses",
    baseUrl: "https://api.openai.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "o3",
        name: "GPT o3",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 40.0,
      },
      {
        id: "o4-mini",
        name: "GPT o4-mini",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
    ],
  },
  {
    key: "openai-chat",
    name: "OpenAI (Chat)",
    description: "GPT 系列 — Chat Completions API",
    icon: "💬",
    apiType: "openai-chat",
    baseUrl: "https://api.openai.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.15,
        costOutput: 0.6,
      },
      {
        id: "o3",
        name: "GPT o3",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 10.0,
        costOutput: 40.0,
      },
      {
        id: "o4-mini",
        name: "GPT o4-mini",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 100000,
        reasoning: true,
        costInput: 1.1,
        costOutput: 4.4,
      },
    ],
  },
  {
    key: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek 系列推理模型",
    icon: "🔵",
    apiType: "openai-chat",
    baseUrl: "https://api.deepseek.com",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek V3",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.27,
        costOutput: 1.1,
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.55,
        costOutput: 2.19,
      },
    ],
  },
  {
    key: "google-gemini",
    name: "Google Gemini",
    description: "Gemini 系列多模态模型",
    icon: "💎",
    apiType: "openai-chat",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    apiKeyPlaceholder: "AIza...",
    requiresApiKey: true,
    models: [
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        inputTypes: ["text", "image", "video"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.15,
        costOutput: 0.6,
      },
    ],
  },
  {
    key: "xai",
    name: "xAI",
    description: "Grok 系列模型",
    icon: "✖️",
    apiType: "openai-chat",
    baseUrl: "https://api.x.ai/v1",
    apiKeyPlaceholder: "xai-...",
    requiresApiKey: true,
    models: [
      {
        id: "grok-4",
        name: "Grok 4",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-4-fast",
        name: "Grok 4 Fast",
        inputTypes: ["text", "image"],
        contextWindow: 2000000,
        maxTokens: 30000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 0.5,
      },
      {
        id: "grok-3",
        name: "Grok 3",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "grok-3-mini",
        name: "Grok 3 Mini",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.5,
      },
      {
        id: "grok-code-fast-1",
        name: "Grok Code Fast",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 10000,
        reasoning: true,
        costInput: 0.2,
        costOutput: 1.5,
      },
    ],
  },
  {
    key: "mistral",
    name: "Mistral",
    description: "Mistral 系列欧洲模型",
    icon: "🟣",
    apiType: "openai-chat",
    baseUrl: "https://api.mistral.ai/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.5,
        costOutput: 1.5,
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "devstral-medium-latest",
        name: "Devstral 2",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "magistral-small",
        name: "Magistral Small",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 40000,
        reasoning: true,
        costInput: 0.5,
        costOutput: 1.5,
      },
      {
        id: "mistral-medium-2508",
        name: "Mistral Medium 3.1",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0.1,
        costOutput: 0.3,
      },
      {
        id: "pixtral-large-latest",
        name: "Pixtral Large",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 2.0,
        costOutput: 6.0,
      },
    ],
  },
  {
    key: "openrouter",
    name: "OpenRouter",
    description: "多模型聚合网关，一个 Key 用数百个模型",
    icon: "🔀",
    apiType: "openai-chat",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyPlaceholder: "sk-or-...",
    requiresApiKey: true,
    models: [
      {
        id: "auto",
        name: "OpenRouter Auto",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "anthropic/claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 3.0,
        costOutput: 15.0,
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 2.5,
        costOutput: 10.0,
      },
      {
        id: "google/gemini-2.5-pro-preview",
        name: "Gemini 2.5 Pro",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 1.25,
        costOutput: 10.0,
      },
      {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.55,
        costOutput: 2.19,
      },
      {
        id: "openrouter/hunter-alpha",
        name: "Hunter Alpha",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "openrouter/healer-alpha",
        name: "Healer Alpha",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "groq",
    name: "Groq",
    description: "超高速 LPU 推理",
    icon: "🚀",
    apiType: "openai-chat",
    baseUrl: "https://api.groq.com/openai",
    apiKeyPlaceholder: "gsk_...",
    requiresApiKey: true,
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.59,
        costOutput: 0.79,
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.24,
        costOutput: 0.24,
      },
    ],
  },
  // ── 国内 Provider ──
  {
    key: "moonshot",
    name: "Moonshot AI (Kimi)",
    description: "Kimi 系列长上下文模型",
    icon: "🌙",
    apiType: "openai-chat",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-thinking-turbo",
        name: "Kimi K2 Thinking Turbo",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 262144,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-turbo",
        name: "Kimi K2 Turbo",
        inputTypes: ["text"],
        contextWindow: 256000,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "qwen",
    name: "通义千问 (Qwen)",
    description: "阿里云 DashScope 大模型",
    icon: "☁️",
    apiType: "openai-chat",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "qwen-max",
        name: "Qwen Max",
        inputTypes: ["text"],
        contextWindow: 32768,
        maxTokens: 8192,
        reasoning: false,
        costInput: 2.4,
        costOutput: 9.6,
      },
      {
        id: "qwen-plus",
        name: "Qwen Plus",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.8,
        costOutput: 2.0,
      },
      {
        id: "qwen-turbo",
        name: "Qwen Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.3,
        costOutput: 0.6,
      },
      {
        id: "qwq-plus",
        name: "QwQ Plus (推理)",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 16384,
        reasoning: true,
        costInput: 1.6,
        costOutput: 4.0,
      },
    ],
    thinkingStyle: "qwen",
  },
  {
    key: "volcengine",
    name: "火山引擎 (豆包)",
    description: "字节跳动 Doubao 系列模型",
    icon: "🌋",
    apiType: "openai-chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "doubao-seed-1-8-251228",
        name: "Doubao Seed 1.8",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "doubao-seed-code-preview-251028",
        name: "Doubao Seed Code",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "deepseek-v3-2-251201",
        name: "DeepSeek V3.2",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "zhipu",
    name: "智谱 AI (Z.AI)",
    description: "GLM 系列模型",
    icon: "🧠",
    apiType: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "glm-5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 1.0,
        costOutput: 3.2,
      },
      {
        id: "glm-5-turbo",
        name: "GLM-5 Turbo",
        inputTypes: ["text"],
        contextWindow: 202800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 1.2,
        costOutput: 4.0,
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "glm-4.7-flash",
        name: "GLM-4.7 Flash",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.07,
        costOutput: 0.4,
      },
      {
        id: "glm-4.7-flashx",
        name: "GLM-4.7 FlashX",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 128000,
        reasoning: true,
        costInput: 0.06,
        costOutput: 0.4,
      },
      {
        id: "glm-4.6",
        name: "GLM-4.6",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "glm-4.6v",
        name: "GLM-4.6V",
        inputTypes: ["text", "image"],
        contextWindow: 128000,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.3,
        costOutput: 0.9,
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 98304,
        reasoning: true,
        costInput: 0.6,
        costOutput: 2.2,
      },
      {
        id: "glm-4.5-flash",
        name: "GLM-4.5 Flash",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 98304,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
    thinkingStyle: "zai",
  },
  {
    key: "minimax",
    name: "MiniMax",
    description: "MiniMax M2 系列模型 (Anthropic 兼容)",
    icon: "🔶",
    apiType: "anthropic",
    baseUrl: "https://api.minimax.io/anthropic",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "MiniMax-M2.7",
        name: "MiniMax M2.7",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "MiniMax-M2.7-highspeed",
        name: "MiniMax M2.7 Highspeed",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "MiniMax-VL-01",
        name: "MiniMax VL 01",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.3,
        costOutput: 1.2,
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0.3,
        costOutput: 1.2,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "kimi-coding",
    name: "Kimi Coding",
    description: "Kimi for Coding (Anthropic 兼容)",
    icon: "🌑",
    apiType: "anthropic",
    baseUrl: "https://api.kimi.com/coding/",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "kimi-code",
        name: "Kimi Code",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "k2p5",
        name: "Kimi Code (legacy)",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
    thinkingStyle: "anthropic",
  },
  {
    key: "xiaomi",
    name: "小米 MiMo",
    description: "MiMo 系列模型",
    icon: "📱",
    apiType: "openai-chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "mimo-v2-pro",
        name: "MiMo V2 Pro",
        inputTypes: ["text"],
        contextWindow: 1048576,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "mimo-v2-omni",
        name: "MiMo V2 Omni",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "mimo-v2-flash",
        name: "MiMo V2 Flash",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "qianfan",
    name: "百度千帆",
    description: "百度智能云 千帆大模型平台",
    icon: "🔴",
    apiType: "openai-chat",
    baseUrl: "https://qianfan.baidubce.com/v2",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        inputTypes: ["text"],
        contextWindow: 98304,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "ernie-5.0-thinking-preview",
        name: "ERNIE 5.0 Thinking",
        inputTypes: ["text", "image"],
        contextWindow: 119000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "modelstudio",
    name: "ModelStudio (DashScope)",
    description: "Alibaba Cloud model service platform with Coding Plan support",
    icon: "🏗️",
    apiType: "openai-chat",
    baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
    apiKeyPlaceholder: "sk-...",
    requiresApiKey: true,
    models: [
      {
        id: "qwen3.5-plus",
        name: "Qwen 3.5 Plus",
        inputTypes: ["text", "image"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-plus",
        name: "Qwen 3 Coder Plus",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-coder-next",
        name: "Qwen 3 Coder Next",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3-max-2026-01-23",
        name: "Qwen 3 Max",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 65536,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        inputTypes: ["text"],
        contextWindow: 1000000,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-5",
        name: "GLM-5",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4.7",
        name: "GLM 4.7",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 16384,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
    thinkingStyle: "qwen",
  },
  {
    key: "nvidia",
    name: "NVIDIA",
    description: "NVIDIA AI Endpoints",
    icon: "💚",
    apiType: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyPlaceholder: "nvapi-...",
    requiresApiKey: true,
    models: [
      {
        id: "nvidia/llama-3.1-nemotron-70b-instruct",
        name: "Llama 3.1 Nemotron 70B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "meta/llama-3.3-70b-instruct",
        name: "Llama 3.3 70B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
        name: "Mistral NeMo Minitron 8B",
        inputTypes: ["text"],
        contextWindow: 8192,
        maxTokens: 2048,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "together",
    name: "Together AI",
    description: "开源模型云推理平台",
    icon: "🤝",
    apiType: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 32768,
        reasoning: true,
        costInput: 0.5,
        costOutput: 2.8,
      },
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7 Fp8",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.45,
        costOutput: 2.0,
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B",
        inputTypes: ["text", "image"],
        contextWindow: 10000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.18,
        costOutput: 0.59,
      },
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick 17B",
        inputTypes: ["text", "image"],
        contextWindow: 20000000,
        maxTokens: 32768,
        reasoning: false,
        costInput: 0.27,
        costOutput: 0.85,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2 Instruct",
        inputTypes: ["text"],
        contextWindow: 262144,
        maxTokens: 8192,
        reasoning: false,
        costInput: 1.0,
        costOutput: 3.0,
      },
    ],
  },
  {
    key: "huggingface",
    name: "Hugging Face",
    description: "HF Inference API 开源模型推理",
    icon: "🤗",
    apiType: "openai-chat",
    baseUrl: "https://router.huggingface.co/v1",
    apiKeyPlaceholder: "hf_...",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.6,
        costOutput: 1.25,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: true,
        costInput: 3.0,
        costOutput: 7.0,
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0.88,
        costOutput: 0.88,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        inputTypes: ["text"],
        contextWindow: 131072,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "byteplus",
    name: "BytePlus (海外火山)",
    description: "BytePlus AI 国际版大模型平台",
    icon: "🔥",
    apiType: "openai-chat",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "seed-1-8-251228",
        name: "Seed 1.8",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 4096,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "chutes",
    name: "Chutes (TEE)",
    description: "TEE 可信执行环境 AI 推理",
    icon: "🔒",
    apiType: "openai-chat",
    baseUrl: "https://llm.chutes.ai/v1",
    apiKeyPlaceholder: "cpk_...",
    requiresApiKey: true,
    models: [
      {
        id: "zai-org/GLM-4.7-TEE",
        name: "GLM-4.7 TEE",
        inputTypes: ["text"],
        contextWindow: 202752,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.4,
        costOutput: 2.0,
      },
      {
        id: "moonshotai/Kimi-K2.5-TEE",
        name: "Kimi K2.5 TEE",
        inputTypes: ["text", "image"],
        contextWindow: 262144,
        maxTokens: 65535,
        reasoning: true,
        costInput: 0.45,
        costOutput: 2.2,
      },
      {
        id: "deepseek-ai/DeepSeek-V3-0324-TEE",
        name: "DeepSeek V3 TEE",
        inputTypes: ["text"],
        contextWindow: 163840,
        maxTokens: 65536,
        reasoning: true,
        costInput: 0.25,
        costOutput: 1.0,
      },
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 40960,
        maxTokens: 40960,
        reasoning: true,
        costInput: 0.08,
        costOutput: 0.24,
      },
    ],
  },
  {
    key: "cloudflare-ai",
    name: "Cloudflare AI Gateway",
    description: "Cloudflare AI 网关代理",
    icon: "☁️",
    apiType: "openai-chat",
    baseUrl: "https://gateway.ai.cloudflare.com/v1/{accountId}/{gatewayId}",
    apiKeyPlaceholder: "...",
    requiresApiKey: true,
    models: [
      {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        inputTypes: ["text", "image"],
        contextWindow: 200000,
        maxTokens: 64000,
        reasoning: true,
        costInput: 3.0,
        costOutput: 15.0,
      },
    ],
  },
  {
    key: "litellm",
    name: "LiteLLM",
    description: "统一 LLM API 代理网关",
    icon: "🔗",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:4000",
    apiKeyPlaceholder: "...",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  // ── 本地 Provider ──
  {
    key: "ollama",
    name: "Ollama",
    description: "本地 + 云端模型推理，无需 API Key",
    icon: "🦙",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:11434",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "glm-4.7-flash",
        name: "GLM 4.7 Flash",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "qwen3:32b",
        name: "Qwen 3 32B",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "kimi-k2.5:cloud",
        name: "Kimi K2.5 (云端)",
        inputTypes: ["text", "image"],
        contextWindow: 256000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "minimax-m2.5:cloud",
        name: "MiniMax M2.5 (云端)",
        inputTypes: ["text"],
        contextWindow: 200000,
        maxTokens: 8192,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
      {
        id: "glm-5:cloud",
        name: "GLM-5 (云端)",
        inputTypes: ["text"],
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "vllm",
    name: "vLLM",
    description: "高性能本地推理引擎",
    icon: "⚙️",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:8000",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
  {
    key: "lm-studio",
    name: "LM Studio",
    description: "桌面端本地模型推理",
    icon: "🖥️",
    apiType: "openai-chat",
    baseUrl: "http://127.0.0.1:1234",
    apiKeyPlaceholder: "（无需填写）",
    requiresApiKey: false,
    models: [
      {
        id: "your-model-id",
        name: "Your Model",
        inputTypes: ["text"],
        contextWindow: 128000,
        maxTokens: 8192,
        reasoning: false,
        costInput: 0,
        costOutput: 0,
      },
    ],
  },
]
